version: '3'
services:
  proxy-collector:
    container_name: proxy-collector
    build:
      context: docker-message-server
      dockerfile: Dockerfile
    image: proxy-collector:latest
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - spring-cloud-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge