parsers:
  freeProxyListConfig:
    url: "https://free-proxy-list.net"
    tableClass: ".fpl-list"
    enabledAnonymities:
      - elite proxy
      - anonymous
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

schedulers:
  proxy-cache:
    internal-state:
      delay: 15000
      initial-delay: 2000